# 𝐋𝐢𝐠𝐡𝐭𝐆𝐁𝐌 𝐀𝐥𝐠𝐨𝐫𝐢𝐭𝐡𝐦 :

- 𝐋𝐢𝐠𝐡𝐭𝐆𝐁𝐌 (𝐋𝐢𝐠𝐡𝐭 𝐆𝐫𝐚𝐝𝐢𝐞𝐧𝐭 𝐁𝐨𝐨𝐬𝐭𝐢𝐧𝐠 𝐌𝐚𝐜𝐡𝐢𝐧𝐞) :

In [1]:
# Import library :
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import lightgbm as lgb

In [2]:
# Load the datasets:
data = load_breast_cancer()
x = data.data
y = data.target

In [3]:
x

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [5]:
# spliting the data into train and testing :
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=12)

In [6]:
# Create a LightGBM model :
train_data = lgb.Dataset(x_train, label=y_train)
params = {
    "objective" : "binary",
    "boosting_type" : "gbdt",
    "metric" : "binary_logloss",
    "num_leaves" : 31,
    "learning_rate" : 0.05,
    "feature_fraction" : 0.9
}

In [7]:
# Train the model :
model = lgb.train(params, train_data, num_boost_round=100)
model

[LightGBM] [Info] Number of positive: 267, number of negative: 159
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001551 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4272
[LightGBM] [Info] Number of data points in the train set: 426, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.626761 -> initscore=0.518344
[LightGBM] [Info] Start training from score 0.518344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best 

In [8]:
# Making predction :
y_pred = model.predict(x_test)
y_pred_binary = [1 if x > 0.5 else 0 for x in y_pred]

In [9]:
# Evaluting the model :
accuracy = accuracy_score(y_test, y_pred_binary)
conf_matrix = confusion_matrix(y_test, y_pred_binary)
class_report = classification_report(y_test, y_pred_binary)

In [11]:
#Print this Evaluting :
print(f"𝐀𝐜𝐜𝐮𝐫𝐚𝐜𝐲: {accuracy}")
print(f"𝐂𝐨𝐧𝐟𝐮𝐬𝐢𝐨𝐧 𝐌𝐚𝐭𝐫𝐢𝐱: \n{conf_matrix}")
print(f"𝐂𝐥𝐚𝐬𝐬𝐢𝐟𝐢𝐜𝐚𝐭𝐢𝐨𝐧 𝐑𝐞𝐩𝐨𝐫𝐭: \n{class_report}")

𝐀𝐜𝐜𝐮𝐫𝐚𝐜𝐲: 0.9230769230769231
𝐂𝐨𝐧𝐟𝐮𝐬𝐢𝐨𝐧 𝐌𝐚𝐭𝐫𝐢𝐱: 
[[45  8]
 [ 3 87]]
𝐂𝐥𝐚𝐬𝐬𝐢𝐟𝐢𝐜𝐚𝐭𝐢𝐨𝐧 𝐑𝐞𝐩𝐨𝐫𝐭: 
              precision    recall  f1-score   support

           0       0.94      0.85      0.89        53
           1       0.92      0.97      0.94        90

    accuracy                           0.92       143
   macro avg       0.93      0.91      0.92       143
weighted avg       0.92      0.92      0.92       143



𝐂𝐨𝐧𝐜𝐞𝐩𝐭 : 𝐋𝐢𝐠𝐡𝐭𝐆𝐁𝐌 (𝐋𝐢𝐠𝐡𝐭 𝐆𝐫𝐚𝐝𝐢𝐞𝐧𝐭 𝐁𝐨𝐨𝐬𝐭𝐢𝐧𝐠 𝐌𝐚𝐜𝐡𝐢𝐧𝐞) is a gradient boosting framework that uses tree-based learning algorithms. It is designed to be efficient and scalable, offering faster training speeds and higher efficiency compared to other gradient boosting algorithms. LightGBM handles large-scale data and offers better accuracy while consuming less memory.

𝐊𝐞𝐲 𝐅𝐞𝐚𝐭𝐮𝐫𝐞𝐬 𝐨𝐟 𝐋𝐢𝐠𝐡𝐭𝐆𝐁𝐌 :
    
- 𝐋𝐞𝐚𝐟-𝐖𝐢𝐬𝐞 𝐓𝐫𝐞𝐞 𝐆𝐫𝐨𝐰𝐭𝐡: Unlike level-wise growth used by other algorithms, LightGBM grows trees leaf-wise, focusing on the leaves with the maximum loss reduction.
- 𝐇𝐢𝐬𝐭𝐨𝐠𝐫𝐚𝐦-𝐁𝐚𝐬𝐞𝐝 𝐃𝐞𝐜𝐢𝐬𝐢𝐨𝐧 𝐓𝐫𝐞𝐞: Uses a histogram-based algorithm to speed up training and reduce memory usage.
- 𝐂𝐚𝐭𝐞𝐠𝐨𝐫𝐢𝐜𝐚𝐥 𝐅𝐞𝐚𝐭𝐮𝐫𝐞 𝐒𝐮𝐩𝐩𝐨𝐫𝐭: Efficiently handles categorical features without needing to preprocess them.
- 𝐎𝐩𝐭𝐢𝐦𝐚𝐥 𝐒𝐩𝐥𝐢𝐭 𝐟𝐨𝐫 𝐌𝐢𝐬𝐬𝐢𝐧𝐠 𝐕𝐚𝐥𝐮𝐞𝐬: Automatically handles missing values and determines the optimal split for them.

𝐊𝐞𝐲 𝐒𝐭𝐞𝐩𝐬 :

- 𝐃𝐞𝐟𝐢𝐧𝐞 𝐭𝐡𝐞 𝐎𝐛𝐣𝐞𝐜𝐭𝐢𝐯𝐞 𝐅𝐮𝐧𝐜𝐭𝐢𝐨𝐧: The loss function to be minimized.
- 𝐂𝐨𝐦𝐩𝐮𝐭𝐞 𝐆𝐫𝐚𝐝𝐢𝐞𝐧𝐭𝐬: Calculate the gradients of the loss function.
- 𝐅𝐢𝐭 𝐭𝐡𝐞 𝐓𝐫𝐞𝐞𝐬: Train decision trees to predict the gradients.
- 𝐔𝐩𝐝𝐚𝐭𝐞 𝐭𝐡𝐞 𝐌𝐨𝐝𝐞𝐥: Combine the predictions of all trees to make the final prediction.

𝐀𝐩𝐩𝐥𝐢𝐜𝐚𝐭𝐢𝐨𝐧𝐬 :
    
    - LightGBM is widely used in various fields such as:
    
- 𝐅𝐢𝐧𝐚𝐧𝐜𝐞: Fraud detection, credit scoring.
- 𝐇𝐞𝐚𝐥𝐭𝐡𝐜𝐚𝐫𝐞: Disease prediction, patient risk stratification.
- 𝐌𝐚𝐫𝐤𝐞𝐭𝐢𝐧𝐠: Customer segmentation, churn prediction.
- 𝐒𝐩𝐨𝐫𝐭𝐬: Player performance prediction, match outcome prediction.