# 𝐍𝐞𝐮𝐫𝐚𝐥 𝐍𝐞𝐭𝐰𝐨𝐫𝐤𝐬(𝐍𝐍) :

In [1]:
# Import Necessart Library :
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
# Import TensorFlow Library:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
# Load the Datasets:
data = load_breast_cancer()
x = data.data
y = data.target

In [4]:
x

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
# Spliting the data into training and testing :
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=12)

In [7]:
# convert the data into StandScaler:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [8]:
# Create the Neural Network (NN) model:
model = Sequential([
    Dense(30, input_shape=(x_train.shape[1],), activation="relu"),
    Dense(15, activation="relu"),
    Dense(1, activation="sigmoid")
])

In [9]:
# Compile the model:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["Accuracy"])

In [10]:
# Train the model:
model.fit(x_train, y_train, epochs=50, batch_size=10, validation_split=0.2, verbose=1)

Epoch 1/50


34/34 [==============================] - 3s 29ms/step - loss: 0.4761 - Accuracy: 0.8265 - val_loss: 0.2983 - val_Accuracy: 0.8837
Epoch 2/50
34/34 [==============================] - 0s 8ms/step - loss: 0.2149 - Accuracy: 0.9471 - val_loss: 0.1831 - val_Accuracy: 0.9302
Epoch 3/50
34/34 [==============================] - 0s 8ms/step - loss: 0.1344 - Accuracy: 0.9676 - val_loss: 0.1404 - val_Accuracy: 0.9302
Epoch 4/50
34/34 [==============================] - 0s 8ms/step - loss: 0.0956 - Accuracy: 0.9853 - val_loss: 0.1203 - val_Accuracy: 0.9535
Epoch 5/50
34/34 [==============================] - 0s 8ms/step - loss: 0.0736 - Accuracy: 0.9824 - val_loss: 0.1059 - val_Accuracy: 0.9535
Epoch 6/50
34/34 [==============================] - 0s 13ms/step - loss: 0.0603 - Accuracy: 0.9853 - val_loss: 0.0946 - val_Accuracy: 0.9535
Epoch 7/50
34/34 [==============================] - 0s 7ms/step - loss: 0.0506 - Accuracy: 0.9853 - val_loss: 0.0863 - val_Accuracy: 0.9651
Epoch 8/50
34/34

In [11]:
# Making prediction:
y_pred = (model.predict(x_test) > 0.5).astype("int32")

5/5 [==============================] - 0s 6ms/step


In [12]:
# Evalution the model:
acuuracy = accuracy_score(y_test, y_pred)
conf_matri = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [13]:
# Print this:
print(f"𝐀𝐜𝐜𝐮𝐫𝐚𝐜𝐲: {acuuracy}")
print(f"𝐂𝐨𝐧𝐟𝐮𝐬𝐢𝐨𝐧 𝐌𝐚𝐭𝐫𝐢𝐱: \n{conf_matri}")
print(f"𝐂𝐥𝐚𝐬𝐬𝐢𝐟𝐢𝐜𝐚𝐭𝐢𝐨𝐧 𝐑𝐞𝐩𝐨𝐫𝐭: \n{class_report}")

𝐀𝐜𝐜𝐮𝐫𝐚𝐜𝐲: 0.965034965034965
𝐂𝐨𝐧𝐟𝐮𝐬𝐢𝐨𝐧 𝐌𝐚𝐭𝐫𝐢𝐱: 
[[49  4]
 [ 1 89]]
𝐂𝐥𝐚𝐬𝐬𝐢𝐟𝐢𝐜𝐚𝐭𝐢𝐨𝐧 𝐑𝐞𝐩𝐨𝐫𝐭: 
              precision    recall  f1-score   support

           0       0.98      0.92      0.95        53
           1       0.96      0.99      0.97        90

    accuracy                           0.97       143
   macro avg       0.97      0.96      0.96       143
weighted avg       0.97      0.97      0.96       143



- 𝐄𝐱𝐚𝐦𝐩𝐥𝐞 𝐰𝐢𝐭𝐡 𝐃𝐫𝐨𝐩𝐨𝐮𝐭 𝐚𝐧𝐝 𝐁𝐚𝐭𝐜𝐡 𝐍𝐨𝐫𝐦𝐚𝐥𝐢𝐳𝐚𝐭𝐢𝐨𝐧 :

In [14]:
from tensorflow.keras.layers import Dropout, BatchNormalization

In [21]:
# Train model:
model = ([
    Dense(30, input_shape=(x_train.shape[1],), activation='relu'),
    BatchNormalization(),
    Dropout(0.5),
    Dense(15, activation="relu"),
    BatchNormalization(),
    Dropout(0.5),
    Dense(1, activation="sigmoid")
])

In [27]:
# Compiling and train reamin the same as before :
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [28]:
# Train the model:
model.fit(x_train, y_train, epochs=50, batch_size=10, validation_split=0.2, verbose=1)

Epoch 1/50
34/34 [==============================] - 4s 22ms/step - loss: 0.1390 - accuracy: 0.9588 - val_loss: 0.0829 - val_accuracy: 0.9535
Epoch 2/50
34/34 [==============================] - 0s 8ms/step - loss: 0.1541 - accuracy: 0.9471 - val_loss: 0.0845 - val_accuracy: 0.9419
Epoch 3/50
34/34 [==============================] - 0s 8ms/step - loss: 0.1733 - accuracy: 0.9353 - val_loss: 0.0829 - val_accuracy: 0.9535
Epoch 4/50
34/34 [==============================] - 0s 9ms/step - loss: 0.1943 - accuracy: 0.9412 - val_loss: 0.0812 - val_accuracy: 0.9535
Epoch 5/50
34/34 [==============================] - 0s 9ms/step - loss: 0.1966 - accuracy: 0.9294 - val_loss: 0.0814 - val_accuracy: 0.9535
Epoch 6/50
34/34 [==============================] - 0s 9ms/step - loss: 0.1725 - accuracy: 0.9500 - val_loss: 0.0795 - val_accuracy: 0.9535
Epoch 7/50
34/34 [==============================] - 0s 10ms/step - loss: 0.1282 - accuracy: 0.9559 - val_loss: 0.0801 - val_accuracy: 0.9651
Epoch 8/50
34/34 [

- 𝐂𝐨𝐧𝐜𝐞𝐩𝐭:
Neural Networks are a set of algorithms, modeled loosely after the human brain, designed to recognize patterns. They interpret sensory data through a kind of machine perception, labeling, or clustering of raw input. The patterns they recognize are numerical, contained in vectors, into which all real-world data, be it images, sound, text, or time series, must be translated.

𝐊𝐞𝐲 𝐅𝐞𝐚𝐭𝐮𝐫𝐞𝐬 𝐨𝐟 𝐍𝐞𝐮𝐫𝐚𝐥 𝐍𝐞𝐭𝐰𝐨𝐫𝐤𝐬 :
    
- 𝐋𝐚𝐲𝐞𝐫𝐬: Composed of an input layer, hidden layers, and an output layer.
- 𝐍𝐞𝐮𝐫𝐨𝐧𝐬: Basic units that take inputs, apply weights, add a bias, and pass through an activation function.
- 𝐀𝐜𝐭𝐢𝐯𝐚𝐭𝐢𝐨𝐧 𝐅𝐮𝐧𝐜𝐭𝐢𝐨𝐧𝐬: Functions applied to the neurons' output, introducing non-linearity (e.g., ReLU, sigmoid, tanh).
- 𝐁𝐚𝐜𝐤𝐩𝐫𝐨𝐩𝐚𝐠𝐚𝐭𝐢𝐨𝐧: Learning algorithm for training the network by minimizing the error.
- 𝐓𝐫𝐚𝐢𝐧𝐢𝐧𝐠: Adjusts weights based on the error calculated from the output and the expected output.

𝐊𝐞𝐲 𝐒𝐭𝐞𝐩𝐬 :
    
- 𝐈𝐧𝐢𝐭𝐢𝐚𝐥𝐢𝐳𝐞 𝐖𝐞𝐢𝐠𝐡𝐭𝐬 𝐚𝐧𝐝 𝐁𝐢𝐚𝐬𝐞𝐬: Start with small random values.
- 𝐅𝐨𝐫𝐰𝐚𝐫𝐝 𝐏𝐫𝐨𝐩𝐚𝐠𝐚𝐭𝐢𝐨𝐧: Pass inputs through the network layers to get predictions.
- 𝐂𝐚𝐥𝐜𝐮𝐥𝐚𝐭𝐞 𝐋𝐨𝐬𝐬: Measure the difference between predictions and actual values.
- 𝐁𝐚𝐜𝐤𝐰𝐚𝐫𝐝 𝐏𝐫𝐨𝐩𝐚𝐠𝐚𝐭𝐢𝐨𝐧: Compute the gradient of the loss function and update weights.
- 𝐈𝐭𝐞𝐫𝐚𝐭𝐢𝐨𝐧: Repeat forward and backward propagation for a set number of epochs or until the loss converges.

𝐀𝐝𝐯𝐚𝐧𝐜𝐞𝐝 𝐅𝐞𝐚𝐭𝐮𝐫𝐞𝐬 𝐨𝐟 𝐍𝐞𝐮𝐫𝐚𝐥 𝐍𝐞𝐭𝐰𝐨𝐫𝐤𝐬:

1. 𝐇𝐲𝐩𝐞𝐫𝐩𝐚𝐫𝐚𝐦𝐞𝐭𝐞𝐫 𝐓𝐮𝐧𝐢𝐧𝐠: Tuning the number of layers, neurons, learning rate, batch size, and epochs for optimal performance.
2. 𝐑𝐞𝐠𝐮𝐥𝐚𝐫𝐢𝐳𝐚𝐭𝐢𝐨𝐧 𝐓𝐞𝐜𝐡𝐧𝐢𝐪𝐮𝐞𝐬: 
   - 𝐃𝐫𝐨𝐩𝐨𝐮𝐭: Randomly drops neurons during training to prevent overfitting.
   - 𝐋𝟏/𝐋𝟐 𝐑𝐞𝐠𝐮𝐥𝐚𝐫𝐢𝐳𝐚𝐭𝐢𝐨𝐧: Adds penalties to the loss function for large weights to prevent overfitting.
3. 𝐄𝐚𝐫𝐥𝐲 𝐒𝐭𝐨𝐩𝐩𝐢𝐧𝐠: Stops training when the validation loss stops improving.
4. 𝐁𝐚𝐭𝐜𝐡 𝐍𝐨𝐫𝐦𝐚𝐥𝐢𝐳𝐚𝐭𝐢𝐨𝐧: Normalizes inputs of each layer to stabilize and accelerate training.

𝐀𝐩𝐩𝐥𝐢𝐜𝐚𝐭𝐢𝐨𝐧𝐬 :
    
Neural Networks are widely used in various fields such as:
    
-  Image classification, object detection, facial recognition.
- Natural Language Processing: Sentiment analysis, language translation, text generation.
- Healthcare: Disease prediction, medical image analysis, drug discovery.
- Finance: Stock price prediction, fraud detection, credit scoring.
- Robotics: Autonomous driving, robotic control, gesture recognition.