# 𝐂𝐚𝐭𝐁𝐨𝐨𝐬𝐭 𝐀𝐥𝐠𝐨𝐫𝐢𝐭𝐡𝐦 :

- 𝐂𝐚𝐭𝐁𝐨𝐨𝐬𝐭 (𝐂𝐚𝐭𝐞𝐠𝐨𝐫𝐢𝐜𝐚𝐥 𝐁𝐨𝐨𝐬𝐭𝐢𝐧𝐠) 𝐢𝐬 𝐚 𝐠𝐫𝐚𝐝𝐢𝐞𝐧𝐭 𝐛𝐨𝐨𝐬𝐭𝐢𝐧𝐠 𝐥𝐢𝐛𝐫𝐚𝐫𝐲.

In [1]:
# Import Library :
import pandas as pd
import numpy as np

In [5]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from catboost import CatBoostClassifier

In [6]:
# Load DAtasets :
data = load_breast_cancer()
x = data.data
y = data.target

In [7]:
x

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [9]:
# Spliting the data into train and test:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=12)

In [11]:
# Create and train the CatBoost model:
model = CatBoostClassifier(iterations=1000, learning_rate=0.1, depth=6, verbose=0)
model.fit(x_train, y_train)

In [12]:
# Making prediction:
y_pred = model.predict(x_test)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int64)

In [13]:
# Evalute the model:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [17]:
# print the model:
print(f"𝐀𝐜𝐜𝐮𝐫𝐚𝐜𝐲: {accuracy}")
print(f"𝐂𝐨𝐧𝐟𝐮𝐬𝐢𝐨𝐧 𝐌𝐚𝐭𝐫𝐢𝐱: \n{conf_matrix}")
print(f"𝐂𝐥𝐚𝐬𝐬𝐟𝐢𝐜𝐚𝐭𝐢𝐨𝐧 𝐑𝐞𝐩𝐨𝐫𝐭: \n{class_report}")

𝐀𝐜𝐜𝐮𝐫𝐚𝐜𝐲: 0.9736842105263158
𝐂𝐨𝐧𝐟𝐮𝐬𝐢𝐨𝐧 𝐌𝐚𝐭𝐫𝐢𝐱: 
[[41  2]
 [ 1 70]]
𝐂𝐥𝐚𝐬𝐬𝐟𝐢𝐜𝐚𝐭𝐢𝐨𝐧 𝐑𝐞𝐩𝐨𝐫𝐭: 
              precision    recall  f1-score   support

           0       0.98      0.95      0.96        43
           1       0.97      0.99      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



𝐂𝐨𝐧𝐜𝐞𝐩𝐭:  CatBoost (𝐂𝐚𝐭𝐞𝐠𝐨𝐫𝐢𝐜𝐚𝐥 𝐁𝐨𝐨𝐬𝐭𝐢𝐧𝐠) is a 𝐆𝐫𝐚𝐝𝐢𝐞𝐧𝐭 𝐁𝐨𝐨𝐬𝐭𝐢𝐧𝐠 library that is particularly effective for datasets that include categorical features. It is designed to handle categorical data natively without the need for extensive preprocessing, such as one-hot encoding, which can lead to better performance and ease of use.

𝐊𝐞𝐲 𝐅𝐞𝐚𝐭𝐮𝐫𝐞𝐬 𝐨𝐟 𝐂𝐚𝐭𝐁𝐨𝐨𝐬𝐭 :
    
- 𝐇𝐚𝐧𝐝𝐥𝐢𝐧𝐠 𝐂𝐚𝐭𝐞𝐠𝐨𝐫𝐢𝐜𝐚𝐥 𝐅𝐞𝐚𝐭𝐮𝐫𝐞𝐬: Uses ordered boosting and a special technique to handle categorical features without needing preprocessing.
- 𝐎𝐫𝐝𝐞𝐫𝐞𝐝 𝐁𝐨𝐨𝐬𝐭𝐢𝐧𝐠: A technique to reduce overfitting by processing data in a specific order.
- 𝐒𝐲𝐦𝐦𝐞𝐭𝐫𝐢𝐜 𝐓𝐫𝐞𝐞𝐬: Ensures efficient memory usage and faster predictions by growing trees symmetrically.
- 𝐑𝐨𝐛𝐮𝐬𝐭 𝐭𝐨 𝐎𝐯𝐞𝐫𝐟𝐢𝐭𝐭𝐢𝐧𝐠: Incorporates techniques to minimize overfitting, making it suitable for various types of data.
- 𝐄𝐟𝐟𝐢𝐜𝐢𝐞𝐧𝐭 𝐆𝐏𝐔 𝐓𝐫𝐚𝐢𝐧𝐢𝐧𝐠: Supports fast training on GPU, which can significantly reduce training time.

𝐊𝐞𝐲 𝐒𝐭𝐞𝐩𝐬 :
- 𝐃𝐞𝐟𝐢𝐧𝐞 𝐭𝐡𝐞 𝐎𝐛𝐣𝐞𝐜𝐭𝐢𝐯𝐞 𝐅𝐮𝐧𝐜𝐭𝐢𝐨𝐧: The loss function to be minimized.
- 𝐂𝐨𝐦𝐩𝐮𝐭𝐞 𝐆𝐫𝐚𝐝𝐢𝐞𝐧𝐭𝐬: Calculate the gradients of the loss function.
- 𝐅𝐢𝐭 𝐭𝐡𝐞 𝐓𝐫𝐞𝐞𝐬: Train decision trees to predict the gradients.
- 𝐔𝐩𝐝𝐚𝐭𝐞 𝐭𝐡𝐞 𝐌𝐨𝐝𝐞𝐥: Combine the predictions of all trees to make the final prediction.

𝐀𝐩𝐩𝐥𝐢𝐜𝐚𝐭𝐢𝐨𝐧𝐬 :

CatBoost is widely used in various fields such as:
- 𝐅𝐢𝐧𝐚𝐧𝐜𝐞: Fraud detection, credit scoring.
- 𝐇𝐞𝐚𝐥𝐭𝐡𝐜𝐚𝐫𝐞: Disease prediction, patient risk stratification.
- 𝐌𝐚𝐫𝐤𝐞𝐭𝐢𝐧𝐠: Customer segmentation, churn prediction.
- 𝐄-𝐜𝐨𝐦𝐦𝐞𝐫𝐜𝐞: Product recommendation, customer behavior analysis.